### ISSUE TITLE
Images look horrible in some cases!

### ISSUE THREAD

**Issue by stephlocke** [lockedatapublished/hugo-lockedata-blog#3]
They are being stretched due to a CSS property override, but not being stretched vertically 
http://lockelife.com/blog/setting-up-wordpress-on-azure/
![image](https://user-images.githubusercontent.com/6452610/29576806-1ce8bdac-8761-11e7-8f2b-039bff18ec51.png)

**Comment by ZoeLocke** [comment]
Steph to work some kind of sorcery on these

**Comment by stephlocke** [comment]
Moved images into repo which has helped substantially
